### ISSUE TITLE
problem: people need to be prodded about abandoning problems

### ISSUE THREAD

**Issue by gsovereignty** [EmurgoHK/emurgobot#10]
problem: people need to be prodded about abandoning problems. This currently happens after 10 days but this is too long for a project using the C4 because it prevents other people from claiming issues if someone has been sidetracked. After 14 days, emurgobot automatically kicks people off a claimed problem if they don't reply after the 10 day warning, at this point the problem goes up for grabs and anyone can claim it, however this is also far too long.

solution: change the 10 day warning to appear after 2 days, and change the 14 day kick to 3 days. In addition, so that people really know the issue is open again, label the issue as "unclaimed".

**Comment by anbud** [comment]
@emurgobot claim

**Comment by anbud** [comment]
Done in #11.
I've updated the config on the production server and restarted the bot.

@emurgobot done
