### ISSUE TITLE
Problem : Remove unclaimed label on claiming issue

### ISSUE THREAD

**Issue by MadanBhandari** [EmurgoHK/emurgobot#12]
Problem : Remove unclaimed label on claim issued
Solution : If issue has unclaimed label, remove unclaimed label before assigning to contributor

**Comment by anbud** [comment]
@emurgobot claim

**Comment by anbud** [comment]
@emurgobot abandone

**Comment by anbud** [comment]
@emurgobot abandon

**Comment by anbud** [comment]
@emurgobot claim

**Comment by anbud** [comment]
@emurgobot claim

**Comment by anbud** [comment]
Done in #13.

@emurgobot done
