### ISSUE TITLE
problem: labels added and then removed

### ISSUE THREAD

**Issue by gsovereignty** [EmurgoHK/emurgobot#14]
problem: when doing an `@emurgobot claim` the `in progress` label is added but then quickly removed.

I thought there might be two instances running or something weird like that but this doesn't appear to be the case.

There are existing changes on the production server, I'm not sure if this is @anbud's work so I'm attactching a diff here. The first diff is plain text diff, the second diff is binary so that the colors are preserved, this can be viewed with `cat binary.bin`

[diff.tar.gz](https://github.com/EmurgoHK/emurgobot/files/2533839/diff.tar.gz)

ping @anbud

**Comment by gsovereignty** [comment]
FYI the IP of the server is 58.152.37.119 and the usual credentials. `screen -r` or `screen -x` should drop you straight into a session running emurgobot in the cli.

**Comment by anbud** [comment]
Yap, I've noticed that this happens sometimes. I'll check it out, I have a possible idea of what's going on. 

@emurgobot claim

**Comment by anbud** [comment]
@emurgobot abandon

**Comment by anbud** [comment]
@emurgobot claim

**Comment by anbud** [comment]
@emurgobot abandon

**Comment by anbud** [comment]
@emurgobot claim

**Comment by anbud** [comment]
@emurgobot claim

**Comment by anbud** [comment]
Fixed in #15.

@emurgobot done

**Comment by anbud** [comment]
@emurgobot claim

**Comment by anbud** [comment]
@emurgobot done
