### ISSUE TITLE
Problem : Emurgobot not working

### ISSUE THREAD

**Issue by MadanBhandari** [EmurgoHK/emurgobot#18]
Problem : emurgobot not working on all EmurgoHK repositories 

ping @gazhayes @anbud

**Comment by anbud** [comment]
I'll fix him, probably just requires a restart or something. :)

**Comment by anbud** [comment]
@gazhayes, the VPS, where @emurgobot is, seems to be down. I can't SSH into it.

**Comment by gsovereignty** [comment]
I will update the IP in 12 hours.
