### ISSUE TITLE
problem: multiple steps required when completing an issue

### ISSUE THREAD

**Issue by gsovereignty** [EmurgoHK/emurgobot#6]
problem: when users complete an issue they need to do emurgobot done and then additionally add the label "done" using emurgobot label "done".

solution: make `@emurgobot done` automatically add the 'done' label.

**Comment by gsovereignty** [comment]
@samuelralak @geekyd you should probably subscribe to this repo, there could be stuff you can help with.

**Comment by samuelralak** [comment]
cool. checking it out

**Comment by dilpreetsio** [comment]
@gazhayes Done :)

**Comment by anbud** [comment]
@emurgobot claim

**Comment by anbud** [comment]
@emurgobot done

**Comment by anbud** [comment]
@emurgobot claim

**Comment by anbud** [comment]
@emurgobot done

**Comment by anbud** [comment]
@emurgobot done

**Comment by anbud** [comment]
@emurgobot done

**Comment by anbud** [comment]
@emurgobot done

**Comment by anbud** [comment]
@emurgobot abandon

**Comment by anbud** [comment]
@emurgobot claim

**Comment by anbud** [comment]
@emurgobot done

**Comment by anbud** [comment]
Done in #7.

@emurgobot done
